### ISSUE TITLE
In which directory should new chokes go?

### ISSUE THREAD

**Issue by Misca1234** [KiCad/Inductors_THT.pretty#6]
What is the intention with 
Choke_Axial_ThroughHole.pretty
Choke_Common:Mode.pretty
Choke_Radial_ThroughHole.pretty
Choke_SMD.pretty
Choke_Toroid.pretty
Inductors_THT.pretty
?

The reason I am asking is that I am looking into Schaffners Current-compensated Chokes
https://www.schaffner.com/products/download/product/datasheet/rn-series-common-mode-chokes-new/

I suspect that new "Chokes" should go into Inductors_THT.pretty and all those "Choke_XXX" are legacy directories ?

**Comment by SchrodingersGat** [comment]
@Misca1234 yes you are correct. The Choke_xxx libs are now all marked as deprecated.
